name: np_platform_message_relay
description: A new Flutter plugin project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0
  np_log:
    path: ../np_log

dev_dependencies:
  build_runner: ^2.4.9
  build_runner_core: ">=7.2.9"
  dart_style: 3.0.1
  np_lints:
    path: ../np_lints
  np_log_build:
    path: ../np_log_build

flutter:
  plugin:
    platforms:
      android:
        package: com.nkming.nc_photos.np_platform_message_relay
        pluginClass: NpPlatformMessageRelayPlugin
      ios:
        pluginClass: NpPlatformMessageRelayPlugin
