name: np_platform_image_processor
description: A new Flutter plugin project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  logging: ^1.2.0
  np_log:
    path: ../np_log
  np_platform_raw_image:
    path: ../np_platform_raw_image
  to_string:
    git:
      url: https://github.com/nkming2/dart-to-string.git
      ref: to_string-1.1.0
      path: to_string

dev_dependencies:
  build_runner: ^2.4.9
  build_runner_core: ">=7.2.9"
  np_lints:
    path: ../np_lints
  np_log_build:
    path: ../np_log_build
  to_string_build:
    git:
      url: https://github.com/nkming2/dart-to-string.git
      ref: to_string_build-1.1.1
      path: to_string_build

flutter:
  plugin:
    platforms:
      android:
        package: com.nkming.nc_photos.np_platform_image_processor
        pluginClass: NpPlatformImageProcessorPlugin
