name: np_db
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: 'none'

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  copy_with:
    git:
      url: https://github.com/nkming2/dart-copy-with.git
      path: copy_with
      ref: copy_with-1.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  logging: ^1.2.0
  np_collection:
    path: ../np_collection
  np_common:
    path: ../np_common
  np_datetime:
    path: ../np_datetime
  np_db_sqlite:
    path: ../np_db_sqlite
  np_log:
    path: ../np_log
  np_string:
    path: ../np_string
  to_string:
    git:
      url: https://github.com/nkming2/dart-to-string.git
      ref: to_string-1.1.0
      path: to_string

dev_dependencies:
  build_runner: ^2.4.9
  build_runner_core: ">=7.2.9"
  copy_with_build:
    git:
      url: https://github.com/nkming2/dart-copy-with.git
      path: copy_with_build
      ref: copy_with_build-1.8.1
  np_lints:
    path: ../np_lints
  np_log_build:
    path: ../np_log_build
  test: ^1.22.1
  to_string_build:
    git:
      url: https://github.com/nkming2/dart-to-string.git
      ref: to_string_build-1.1.1
      path: to_string_build
