name: np_collection
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  collection: ^1.15.0
  np_math:
    path: ../np_math
  quiver: ^3.2.1
  tuple: ^2.0.1

dev_dependencies:
  np_lints:
    path: ../np_lints
  test: ^1.21.0
