name: np_platform_image_format_jxl
description: "A new Flutter plugin project."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0
  np_common:
    path: ../np_common
  np_image_format_interface:
    path: ../np_image_format_interface
  np_log:
    path: ../np_log
  np_platform_raw_image:
    path: ../np_platform_raw_image
  plugin_platform_interface: ^2.0.2
  to_string:
    git:
      url: https://github.com/nkming2/dart-to-string.git
      ref: to_string-1.1.0
      path: to_string

dev_dependencies:
  analyzer: ^6.2.0
  build_runner: ^2.4.9
  np_lints:
    path: ../np_lints
  np_log_build:
    path: ../np_log_build
  pigeon: ^22.6.0
  to_string_build:
    git:
      url: https://github.com/nkming2/dart-to-string.git
      ref: to_string_build-1.1.1
      path: to_string_build

flutter:
  plugin:
    platforms:
      android:
        package: com.nkming.nc_photos.np_platform_image_format_jxl
        pluginClass: NpPlatformImageFormatJxlPlugin
