name: np_log_build
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  analyzer: ^6.2.0
  build: ^2.4.1
  np_log:
    path: ../np_log
  source_gen: ^1.5.0

dev_dependencies:
  build_test: ^2.1.5
  np_lints:
    path: ../np_lints
  path: ^1.8.3
  test: ^1.22.1
