include: package:flutter_lints/flutter.yaml

linter:
  rules:
    unawaited_futures: true
    avoid_void_async: true
    depend_on_referenced_packages: false
    prefer_interpolation_to_compose_strings: false
    no_leading_underscores_for_local_identifiers: false
    use_build_context_synchronously: false
    directives_ordering: true
