include: package:np_lints/np.yaml

linter:
  rules:
    prefer_interpolation_to_compose_strings: false
    no_leading_underscores_for_local_identifiers: false
    use_build_context_synchronously: false
