name: np_common
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:

dev_dependencies:
  np_lints:
    path: ../np_lints
  test: any
