name: np_common
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  to_string:
    git:
      url: https://gitlab.com/nkming2/dart-to-string
      ref: to_string-1.0.0
      path: to_string

dev_dependencies:
  build_runner: ^2.2.1
  np_lints:
    path: ../np_lints
  test: ^1.21.0
  to_string_build:
    git:
      url: https://gitlab.com/nkming2/dart-to-string
      ref: to_string_build-1.0.0
      path: to_string_build
