name: np_common
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  to_string:
    git:
      url: https://github.com/nkming2/dart-to-string.git
      ref: to_string-1.1.0
      path: to_string

dev_dependencies:
  analyzer: ^6.2.0
  build_runner: ^2.4.9
  build_runner_core: ">=7.2.9"
  np_lints:
    path: ../np_lints
  test: ^1.22.1
  to_string_build:
    git:
      url: https://github.com/nkming2/dart-to-string.git
      ref: to_string_build-1.1.1
      path: to_string_build
