name: np_api
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  http: ^0.13.5
  logging: any
  np_codegen:
    path: ../codegen
  np_common:
    path: ../np_common
  np_log:
    path: ../np_log
  np_string:
    path: ../np_string
  to_string:
    git:
      url: https://gitlab.com/nkming2/dart-to-string
      ref: to_string-1.0.0
      path: to_string
  xml: ^6.1.0

dev_dependencies:
  build_runner: ^2.2.1
  np_codegen_build:
    path: ../codegen_build
  np_lints:
    path: ../np_lints
  test: any
  to_string_build:
    git:
      url: https://gitlab.com/nkming2/dart-to-string
      ref: to_string_build-1.0.0
      path: to_string_build
