name: np_ui
description: Generic UI widgets and theming support package
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  np_common:
    path: ../np_common

dev_dependencies:
  np_lints:
    path: ../np_lints
